Making library comptatible with actix-web 1.0
actix/actix-protobuf pull request #3
Opened 2019-05-18 12:44 UTC by hstefan

2019-05-18 16:41 UTC, fafhrd91 commented on Cargo.toml
> +actix-web = "1.0.0-b3"
1.0.0-beta5

2019-05-18 16:41 UTC, fafhrd91 requested changes
could you also remove travis config for 1.21

2019-05-18 17:29 UTC, hstefan commented
@fafhrd91 should be good now!

2019-05-18 17:35 UTC, fafhrd91 commented
looks good. could you add entry to changes

2019-05-18 17:35 UTC, fafhrd91 approved these changes

2019-05-18 20:31 UTC, hstefan commented
@fafhrd91 done, should be good to merge now

2019-05-18 21:37 UTC, otavio commented on Cargo.toml
> +actix-web = "1.0.0-b3"
`1.0.0-rc` now

2019-05-18 22:06 UTC, hstefan commented on Cargo.toml
> +actix-web = "1.0.0-b3"
Thinks move so fast! Bumped again.

2019-05-19 15:36 UTC, fafhrd91 approved these changes

2019-05-19 15:36 UTC, merged

2019-05-19 15:36 UTC, fafhrd91 commented
thanks!